stages:
  - test
  - build

variables:
  NODE_ENV: test

# Backend Tests
backend_tests:
  stage: test
  image: node:20-alpine
  before_script:
    - cd backend
    - npm install
  script:
    - npm test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      branches:
        - main
        - dev
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

# Backend Build
backend_build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker build -t backend ./backend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      branches:
        - main
        - dev
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
