stages:
  - test
  - build

variables:
  NODE_ENV: test

# Frontend Tests
frontend_tests:
  stage: test
  image: node:20-alpine
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev")'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

# Frontend Build
frontend_build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker build -t frontend ./frontend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev")'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
