sonar.projectKey=smoosy75_tdd-test-qualite
sonar.organization=smoosy75

sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,frontend/src
sonar.test.inclusions=**/*.test.*,**/*.spec.*
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
